runtime: python39
entrypoint: gunicorn -b :$PORT main:app --timeout 120 --log-level=debug
instance_class: F4_1G

handlers:
- url: /(.*\.(json|ico|js))$
  static_files: frontend/build/\1
  upload: frontend/build/.*\.(json|ico|js)$
- url: /
  static_files: frontend/build/index.html
  upload: frontend/build/index.html
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
